name: Feature as User Story
description: Suggest a feature from the user perspective
title: "[Feature]: "
labels: ["feature"]
projects: ["Progress-Hous/9"]
body:
  - type: markdown
    attributes:
      value: |
        Before submitting a `feature`, please make sure there is no existing feature for the one you are requesting. If so, please provide the following information:
  - type: dropdown
    id: role
    attributes:
      label: "As a "
      options:
        - 'User [logged in]'
        - 'User [not logged in]'
        - 'Technical Team Member'
      default: 0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "_____________"
      description: "Format: 'As a [role], I want / would like [feature], so that [reason].' Specify requirements."
      value: "I want to "
    validations:
      required: true
  - type: textarea
    id: criteria
    attributes:
      label: "List of Acceptance Criteria"
      description: "list of tasks to check off."
      placeholder: "- [ ] include unit tests checking..."
    validations:
      required: true
  - type: textarea
    id: examples
    attributes:
      label: "Examples / Docs / links / tutorials"
      description: "sample implementation, documentation, links to YouTube."
    validations:
      required: false
  - type: textarea
    id: feedback
    attributes:
      label: "Additional Comments"
      description: "something that doesn't fit in the rest of the fields"