name: Feature as User Story
description: Suggest a feature from the user perspective
title: "[User Story]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        **Guidelines**: Before submitting, ensure your story is new and aligns with the project's goals.
  - type: dropdown
    id: role
    attributes:
      label: "As a "
      options:
        - 'User [logged in]'
        - 'User [not logged in]'
        - 'Technical Team Member'
    validations:
      required: true
  - type: textarea
    id: user_story
    attributes:
      label: " "
      description: "Format: 'As a [role], I want / would like [feature], so that [reason].' Specify requirements."
      value: "I want to "
    validations:
      required: true
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "List of Acceptance Criteria"
      description: "list of tasks to check off."
      placeholder:  |
        - [] include unit tests checking...
        - [] include integration tests...
    validations:
      required: true
  - type: textarea
    id: examples
    attributes:
      label: "Examples / Docs / links / tutorials"
      description: "sample implementation, documentation, links to YouTube."
    validations:
      required: false
  - type: textarea
    id: additional_comments
    attributes:
      label: "Additional Comments"
      description: "something that doesn't fit in the rest of the fields"