name: Feature as User Story
description: write user-story from selected user perspective
title: "[Feature]: "
labels: ["feature"]
projects: ["Progress-House/9"]

body:
  - type: markdown
    attributes:
      value: |
        Before submitting a `feature`, please make sure there is no existing feature for the one you are requesting. If so, please provide the following information:
  - type: dropdown
    id: role
    attributes:
      label: "As a "
      options:
        - 'User [logged in]'
        - 'User [not logged in]'
        - 'Technical Team Member'
      default: 0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "I would like to"
    validations:
      required: true
  - type: textarea
    id: criteria
    attributes:
      label: "List of Acceptance Criteria"
      description: "list of tasks to check off."
      placeholder: "- [ ] include unit tests checking..."
    validations:
      required: true
  - type: textarea
    id: examples
    attributes:
      label: "Examples / Docs / links / tutorials"
      description: "sample implementation, documentation, links to YouTube, github."
    validations:
      required: false
  - type: textarea
    id: feedback
    attributes:
      label: "Additional Comments"
      description: "something that doesn't fit in the rest of the fields"
    validations:
      required: false